name: Deploy Application Docker Image using GHCR (Free)

on:
  push:
    branches: [main]

jobs:
  Continuous-Integration:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and push Docker image to GHCR
        run: |
          docker build -t ghcr.io/shivamgupta8689/vehicle-insurance-prediction:latest .
          docker push ghcr.io/shivamgupta8689/vehicle-insurance-prediction:latest

  Continuous-Deployment:
    needs: Continuous-Integration
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Pull and run Docker container
        run: |
          docker pull ghcr.io/shivamgupta8689/vehicle-insurance-prediction:latest
          docker stop mlops-app || true
          docker rm mlops-app || true
          docker run -d --name mlops-app \
            -e MONGODB_URL="${{ secrets.MONGODB_URL }}" \
            -p 5000:5000 ghcr.io/shivamgupta8689/vehicle-insurance-prediction:latest
